# Generated by Django 4.2.4 on 2023-08-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
